version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directory: "/at-buildimage/"
    schedule:
      interval: "daily"
    groups:
      docker:
        patterns:
          - "*"
