version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directories:
      - "/at-buildimage/"
      - "/valgrind/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*" # Applies to all Docker images
        versions: ["*beta*"] # Ignore versions that include 'beta'
    groups:
      docker:
        patterns:
          - "*"
