version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directories:
      - "/at-buildimage/"
      - "/valgrind/"
      - "/caddy-do-dns/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    groups:
      docker:
        patterns:
          - "*"
