name: AutoBuildAll

on:
  workflow_dispatch:
  push:
    branches:
      - trunk
    paths:
      - 'at-buildimage/Dockerfile'

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  get_stable_version:
    runs-on: ubuntu-latest
    outputs:
      dartversion: ${{ steps.dartversion.outputs.dartversion }}
    steps:
      - id: dartversion
        name: Get stable version
        run: |
          DDURL="https://raw.githubusercontent.com/dart-lang/dart-docker/main/versions.json"
          DART_VERSION=$(curl -s $DDURL | jq -r .stable.version)
          echo "dartversion=${DART_VERSION}" >> $GITHUB_OUTPUT

  build_multi_arch_images:
    needs: [get_stable_version]
    env:
      DART_VERSION: ${{ needs.get_stable_version.outputs.dartversion }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # for creating OIDC tokens for signing.
    steps:
      - name: Install cosign
        uses: sigstore/cosign-installer@cad07c2e89fa2edd6e2d7bab4c1aa38e53f76003 # v4.1.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Login to DockerHub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Metadata (tags, labels) for buildimage
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          tags: |
            type=raw,value=automated
            type=raw,value=${{ env.DART_VERSION }}
            type=raw,value=GHA_${{ github.run_number }}
          images: |
            atsigncompany/buildimage
          labels: |
            org.opencontainers.image.description=Dart Build Image

      - name: Build and push Multi Arch buildimage
        id: docker_build
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          file: ./at-buildimage/Dockerfile
          push: true
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          platforms: |
            linux/amd64
            linux/arm64/v8
            linux/arm/v7
            linux/riscv64

      - name: Sign buildimage images with GitHub OIDC Token
        env:
          DIGEST: ${{ steps.docker_build.outputs.digest }}
          TAGS: ${{ steps.meta.outputs.tags }}
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes ${images}

      - name: Metadata (tags, labels) for dartshowplatform
        id: meta_sp
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          tags: |
            type=raw,value=automated
            type=raw,value=${{ env.DART_VERSION }}
            type=raw,value=GHA_${{ github.run_number }}
          images: |
            atsigncompany/dartshowplatform
          labels: |
            org.opencontainers.image.description=Dart Show Platform application

      - name: Build and push dartshowplatform
        id: docker_build_sp
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          file: ./dartshowplatform/Dockerfile
          push: true
          provenance: false
          tags: ${{ steps.meta_sp.outputs.tags }}
          platforms: |
            linux/amd64
            linux/arm64/v8
            linux/arm/v7
            linux/riscv64

      - name: Sign showplatform images with GitHub OIDC Token
        env:
          DIGEST: ${{ steps.docker_build_sp.outputs.digest }}
          TAGS: ${{ steps.meta_sp.outputs.tags }}
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes ${images}

      - name: Google Chat Notification
        uses: Co-qn/google-chat-notification@3691ccf4763537d6e544bc6cdcccc1965799d056 # releases/v1
        with:
          name: New images build for Dart SDK ${{ env.DART_VERSION }}
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}
