name: AutoBuildAll

on:
  workflow_dispatch:
  schedule:
    - cron: '42 7 * * *' # At 0742 each day

jobs:
  check_for_new_stable:
    runs-on: ubuntu-latest
    outputs:
      dartversion: ${{ steps.dartversion.outputs.dartversion }}
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.

      - id: dartversion
        name: Check stable version
        run: |
          DDURL="https://raw.githubusercontent.com/dart-lang/dart-docker/main/versions.json"
          curl -s $DDURL | jq -r .stable.version > DART_STABLE_VERSION
          if [ -z "$(git status --porcelain)" ]; then 
            echo 'No new stable release of Dart'
            echo "::set-output name=dartversion::NOTNEW"
            exit 0
          else
            DART_VERSION=$(cat DART_STABLE_VERSION)
            echo "::set-output name=dartversion::$DART_VERSION"
          fi          
  
  build_multi_arch_images:
    needs: [check_for_new_stable]
    if: ${{ needs.check_for_new_stable.outputs.dartversion != 'NOTNEW' }}
    env:
      DART_VERSION: ${{ needs.check_for_new_stable.outputs.dartversion }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push buildimage
        id: docker_build1
        uses: docker/build-push-action@v3.2.0
        with:
          file: ./at-buildimage/Dockerfile
          build-args: DART_VERSION=${{ env.DART_VERSION }}
          push: true
          tags: |
            atsigncompany/buildimage:automated
            atsigncompany/buildimage:${{ env.DART_VERSION }}
            atsigncompany/buildimage:GHA_${{ github.run_number }}
          platforms: |
            linux/amd64
            linux/arm64/v8
            linux/arm/v7

      - name: Build and push dartshowplatform
        id: docker_build3
        uses: docker/build-push-action@v3.2.0
        with:
          file: ./dartshowplatform/Dockerfile
          build-args: DART_VERSION=${{ env.DART_VERSION }}
          push: true
          tags: |
            atsigncompany/dartshowplatform:automated
            atsigncompany/dartshowplatform:${{ env.DART_VERSION }}
            atsigncompany/dartshowplatform:GHA_${{ github.run_number }}
          platforms: |
            linux/amd64
            linux/arm64/v8
            linux/arm/v7

      - name: Google Chat Notification
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: New images build for Dart SDK ${{ env.DART_VERSION }}
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}

  update_version_in_repo:
    needs: [check_for_new_stable, build_multi_arch_images]
    env:
      DART_VERSION: ${{ needs.check_for_new_stable.outputs.dartversion }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout_to_update_version
        uses: actions/checkout@v3 # checkout the repository content to github runner.

      - name: Update stable version
        id: dartversion
        run: |
          echo "$DART_VERSION" > DART_STABLE_VERSION

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          commit-message: 'chore: Bump DART_VERSION file to match latest Stable release'
          committer: library-action[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: library-action[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          signoff: false
          add-paths: .
          branch: bot-new-stable-version
          delete-branch: true
          title: 'chore: New DART_STABLE_VERSION'
          body: |
            Bumping version tracking file after updating Docker images.
          labels: |
            operations
          assignees: cpswan
          reviewers: gkc
          draft: false