name: Caddy

on:
  workflow_dispatch:
  push:
    branches:
      - trunk
    paths:
      - 'caddy-do-dns/Dockerfile'

permissions: # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  build_images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # for creating OIDC tokens for signing.
    steps:
      - name: Install cosign
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Login to DockerHub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          tags: |
            type=raw,value=latest
            type=raw,value=GHA_${{ github.run_number }}
          images: |
            atsigncompany/caddy-do-dns
          labels: |
            org.opencontainers.image.description=Caddy with DigitalOcean DNS

      - name: Build and push Multi Arch images
        id: docker_build
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          file: ./caddy-do-dns/Dockerfile
          push: true
          provenance: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: |
            linux/amd64

      - name: Sign the images with GitHub OIDC Token
        env:
          DIGEST: ${{ steps.docker_build.outputs.digest }}
          TAGS: ${{ steps.meta.outputs.tags }}
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes ${images}
